name: Build CV

on:
  push:
    paths:
      - 'cv.md'
  workflow_dispatch:

jobs:
  convert_to_pdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Convert MD to PDF
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: cv.md
          output_dir: files
          build_html: false
      
      - name: Commit PDF
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add files/cv.pdf
          git commit -m "Automated CV update" || exit 0
          git push 