name: Build CV

on:
  push:
    paths:
      - 'cv.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install md-to-pdf
        run: npm install -g md-to-pdf
      
      - name: Create files directory
        run: mkdir -p files
      
      - name: Convert MD to PDF
        run: md-to-pdf cv.md --output files/cv.pdf
      
      - name: Commit PDF
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add files/cv.pdf
          git commit -m "Automated CV update" || exit 0
          git push 